### ISSUE TITLE
Search/Filter user list

### ISSUE THREAD

**Issue by neumantm** [spethso/Drinklist#30]
I would be nice if one could filter the list of users by a text input field.
One could search himself faster that way.

**Comment by mee4895** [comment]
Only relevant on small screens. This is related to: https://github.com/spethso/Drinklist/issues/33

**Comment by neumantm** [comment]
In my opinion this is not only relevant on small screens. Even on a large screen it can be hard to find a name and it would be easier/faster if there was the possibility to search.

**Comment by mee4895** [comment]
This as well as https://github.com/spethso/Drinklist/issues/33 will probably require quite substantial rewrites of the front-end so it will take some time to fix.
