### ISSUE TITLE
Backup API call results in 404 error

### ISSUE THREAD

**Issue by TheSeven** [spethso/Drinklist#49]
https://github.com/spethso/Drinklist/blob/33b49acbfe635d91b6c02db01ed6ef1ae19ecb91/src/adminPage/app/controllers/main.js#L65
$scope.api ends with a slash, and the backend doesn't like the resulting double-slash. Maybe this should be ./backup?

**Comment by mee4895** [comment]
Fixed by: https://github.com/spethso/Drinklist/commit/50eabbfb10aa0a5d262faede160ed080af449a89
