### ISSUE TITLE
Downloading DB Dump Fails

### ISSUE THREAD

**Issue by marzipankaiser** [spethso/Drinklist#52]
In the admin interface, clicking the "Download DB Dump" Button does not download a DB Dump but the admin is not logged in afterwards.

**Comment by mee4895** [comment]
Already solved by @st116290 with: https://github.com/spethso/Drinklist/commit/50eabbfb10aa0a5d262faede160ed080af449a89 & https://github.com/spethso/Drinklist/commit/c5d8e0c78a2f3d8c0eb3b06e41621220747bb981
The FS Website simply was not updated
