### ISSUE TITLE
Allow for administrator to add footer with links to legal documents

### ISSUE THREAD

**Issue by neumantm** [spethso/Drinklist#53]
By the EU General Data Protection Regulation, it is necessary to have a link on every public webpage, pointing to a document explaing what data is collected. Additionaly you need to link to your imprint page.

It would be nice, if the Pizza Calculator would provide a possibility for the admin to configure such links.
For example in a configuration file.

**Comment by mee4895** [comment]
This is NOT the Pizza Calculator and the link is NOT in the footer but never the less this is done here: https://github.com/spethso/Drinklist/commit/cb1553ca76313cbbdc24427205178de0c872095a
